apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
  {{- end }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: {{ .Values.name }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - podAffinityTerm:
      #         labelSelector:
      #           matchExpressions:
      #           - key: app
      #             operator: In
      #             values:
      #             - {{ .Values.name }}
      #         topologyKey: topology.kubernetes.io/zone
      #       weight: 100
      containers:
      - name: {{ .Values.name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ .Values.name }}
        ports:
          - name: http
            containerPort: {{ .Values.containers.port }}
            protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: {{ .Values.healthcheck.path }}
        #     port: http
        readinessProbe:
          httpGet:
            path: {{ .Values.healthcheck.path }}
            port: {{ .Values.containers.port }}
          initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
          failureThreshold: {{ .Values.healthcheck.failureThreshold }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        # resizePolicy:
        # - resourceName: "cpu"
        #   restartPolicy: "NotRequired"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
