apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.secretsManager }}  # aws secretsManager
      metadataPolicy: None
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .Values.name }} # secret
